### ISSUE TITLE
Push docs to msmbuilder.org

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/osprey#100]
The last successful build was 6 months ago. @rmcgibbo: 1) How can I become an admin for this project on ReadTheDocs and 2) any ideas?

Seems to be [failing](http://readthedocs.org/projects/osprey/builds/3781881/) to install `numpy`:
```
Building wheels for collected packages: numpy, scipy, scikit-learn, sqlalchemy
  Running setup.py bdist_wheel for numpy
  Stored in directory: /home/docs/checkouts/readthedocs.org/user_builds/osprey/.cache/pip/wheels/66/f5/d7/f6ddd78b61037fcb51a3e32c9cd276e292343cdd62d5384efd
  Running setup.py bdist_wheel for scipy
  Complete output from command /home/docs/checkouts/readthedocs.org/user_builds/osprey/envs/master/bin/python -c "import setuptools;__file__='/tmp/pip-build-bhTBoJ/scipy/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpFpfE9apip-wheel-:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-bhTBoJ/scipy/setup.py", line 265, in <module>
      setup_package()
    File "/tmp/pip-build-bhTBoJ/scipy/setup.py", line 253, in setup_package
      from numpy.distutils.core import setup
  ImportError: No module named numpy.distutils.core
```

**Comment by rmcgibbo** [comment]
rtd + numpy is a mess that doesn't really work. best option is to probably
just build the docs inside travis like msmbuilder/mdtraj.

On Wed, Mar 2, 2016 at 11:01 PM, Carlos Hernández <notifications@github.com>
wrote:

> The last successful build was 6 months ago. @rmcgibbo
> <https://github.com/rmcgibbo>: 1) How can I become an admin for this
> project on ReadTheDocs and 2) any ideas?
>
> Seems to be failing to install numpy:
>
> Building wheels for collected packages: numpy, scipy, scikit-learn, sqlalchemy
>   Running setup.py bdist_wheel for numpy
>   Stored in directory: /home/docs/checkouts/readthedocs.org/user_builds/osprey/.cache/pip/wheels/66/f5/d7/f6ddd78b61037fcb51a3e32c9cd276e292343cdd62d5384efd
>   Running setup.py bdist_wheel for scipy
>   Complete output from command /home/docs/checkouts/readthedocs.org/user_builds/osprey/envs/master/bin/python -c "import setuptools;__file__='/tmp/pip-build-bhTBoJ/scipy/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpFpfE9apip-wheel-:
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "/tmp/pip-build-bhTBoJ/scipy/setup.py", line 265, in <module>
>       setup_package()
>     File "/tmp/pip-build-bhTBoJ/scipy/setup.py", line 253, in setup_package
>       from numpy.distutils.core import setup
>   ImportError: No module named numpy.distutils.core
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pandegroup/osprey/issues/100>.
>



-- 
-Robert

**Comment by cxhernandez** [comment]
What's the protocol for getting domain names? Do we have a PG namecheap account?

**Comment by mpharrigan** [comment]
I'll deploy to msmbuilder.org/osprey

**Comment by cxhernandez** [comment]
+1

**Comment by cxhernandez** [comment]
fixed in https://github.com/msmbuilder/osprey/pull/108 and https://github.com/msmbuilder/osprey/pull/113

**Comment by mpharrigan** [comment]
I added an `index.html` that goes to the latest released version. I had to fudge it a bit because we don't really have docs from the latest released version, so I copied the most recently generated docs to "0.4". It shows that the dropdown and autoredirect to latest-released-version is working, but the version number in the supposed 0.4 docs is reported as 1.0.0.dev0

When we release 1.0, I'll delete the alleged 0.4 docs

http://msmbuilder.org/osprey
