### ISSUE TITLE
Merge Osprey with MSMBuilder

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/osprey#101]
This was brought up as a possibility while discussing https://github.com/pandegroup/osprey/issues/100. Consolidating the two repos would be nice because they're fairly complimentary and directing people to another set of documentation seems somewhat cumbersome from a UX perspective.

On the other hand, osprey isn't limited to working with MSMs....

**Comment by mpharrigan** [comment]
What if we move the repository to the msmbuilder "organization", push docs to msmbuilder.org/osprey/ but keep it a separate package. maybe we can make it a dependency of msmbuilder (but not vice-versa)

**Comment by cxhernandez** [comment]
+1
