### ISSUE TITLE
Logo for docs

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/osprey#114]

**Comment by cxhernandez** [comment]
![image](https://cloud.githubusercontent.com/assets/5142365/13856915/c0b33422-ec34-11e5-8a5f-bcecccd60da9.png)

I have this in an svg, so we can easy change the colors (I went for the msmbuilder color scheme for now).

**Comment by mpharrigan** [comment]
cool. maybe tone down the colors

**Comment by cxhernandez** [comment]
![image](https://cloud.githubusercontent.com/assets/5142365/13857995/ad32cf2a-ec39-11e5-8719-59cb1fc21b36.png)

This better?

**Comment by mpharrigan** [comment]
Looks good. A minor nitpick is it's a little "tall"

**Comment by cxhernandez** [comment]
![osprey](https://cloud.githubusercontent.com/assets/5142365/13860757/350b12ce-ec47-11e5-89d5-78fdd8d2a479.png)


Okay, I think I managed to make the wings smaller without making it look silly.

**Comment by msultan** [comment]
Should the logo have something descriptive like "automated hyperparamter optimization"?

**Comment by cxhernandez** [comment]
I'm generally opposed to having so much text in a logo, but where would you add it?

**Comment by msultan** [comment]
Maybe to the right side of the bird?

**Comment by cxhernandez** [comment]
> Maybe to the right side of the bird?

ehh.....

done in https://github.com/msmbuilder/osprey/pull/116
