### ISSUE TITLE
Problem with doc deployment

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/osprey#118]
Somehow, the top level `index.html` that is supposed to redirect to `development/` or `0.4/` got overwritten

**Comment by mpharrigan** [comment]
I manually put it back, but we should figure out why that happened

**Comment by cxhernandez** [comment]
That was my fault! Sorry!

**Comment by mpharrigan** [comment]
Seriously, be careful tho. That code's not under revision control*. 
 
`*` asterisk: except I periodically sync it to my local machine which is under git. If anyone else wants so, theres a file "sync.sh" that uses amazons aws command line
