### ISSUE TITLE
current_best fails if the estimator is not a Pipeline

### ISSUE THREAD

**Issue by kudkudak** [msmbuilder/osprey#121]
Hello,

`current_best` command fails for `example/config_1.yaml`. I think it should be checked here https://github.com/msmbuilder/osprey/blob/master/osprey/execute_currentbest.py#L24 if the estimator has steps field.

**Comment by cxhernandez** [comment]
Thanks @kudkudak! Working on a PR now...

**Comment by cxhernandez** [comment]
fixed in #122
