### ISSUE TITLE
sparse matrix dataset support

### ISSUE THREAD

**Issue by kudkudak** [msmbuilder/osprey#123]
Hello,

If BaseDatasetLoader returns sparse matrix it fails in https://github.com/msmbuilder/osprey/blob/master/osprey/config.py#L282 with `TypeError: sparse matrix length is ambiguous; use getnnz() or shape[0]` 

EDIT: same in `execute_worker.py` and `cross_validation.py`

**Comment by cxhernandez** [comment]
@kudkudak: The easiest way to create sparse matrix support would be to create your own [dataset loader](https://github.com/msmbuilder/osprey/blob/master/osprey/dataset_loaders.py) that extracts the sparse matrix as a NumPy array.

As far as supporting sparse matrices internally in Osprey, I'd be happy to consider any PRs :smiley:

**Comment by kudkudak** [comment]
That's true, but the matrix could be prohibitively large. I think the only change needed to support sparse is changing `len(X)` to `X.shape[0]` (at least it worked on simple worker cmd), but this will break things if the dataset can be something different than np or csr matrix. 

I think there are two approaches, either it is assumed that everything has `shape` (is np.ndarray or sparse matrix), or there is a simple utility function that will check if this is sparse matrix and call shape in this case.

Btw. creating own dataset loader is slightly cumbersome as the only way to add this without modyfing package is creating own CLI that imports custom classes. I think adding `eval` option for `dataset`and `cv` would be cool.

**Comment by rmcgibbo** [comment]
This seems like a good idea.

**Comment by cxhernandez** [comment]
>  simple utility function that will check if this is sparse matrix and call shape in this case

This is probably the way to go. The other datasets currently passed through are `Trajectory` objects from MDTraj, which don't have a `shape` property.

> I think adding eval option for dataset_loaderand cv would be cool.

Agreed!

**Comment by cxhernandez** [comment]
fixed in https://github.com/msmbuilder/osprey/pull/126
