### ISSUE TITLE
more helpful response to tica lag time CV

### ISSUE THREAD

**Issue by brookehus** [msmbuilder/osprey#140]
This error message stops a given osprey run:
```
File "/home/bhusic/source/msmbuilder/msmbuilder/decomposition/tica.py", line 282, in fit
'the lag time, %d' % self.lag_time)
ValueError: All sequences were shorter than the lag time, 2129
```

Osprey should run a check on the config file to make sure that if tica__lag_time is specified, that its upper bound is less than, e.g., the shortest sequence. Or maybe, if osprey runs into this problem during a run, it should choose a new lag time until one works.

**Comment by sryckbos** [comment]
Does it currently stop an osprey run?  That seems weird to me; I believe we talked about this before (see https://github.com/msmbuilder/msmbuilder/pull/469) and the conclusion was to have a warning that a given trajectory is too short for the tica lag time.  Did we change that back? I think the better thing to do here would be just to discount the given trajectory and give a warning; if you have a handful of short trajectories I would say that shouldn't automatically discount short tica lag times.

**Comment by brookehus** [comment]
> Does it currently stop an osprey run? 
It doesn't shut down osprey, it just moves to the next set of parameter choices. But this could result in a small percentage of parameter choices outputting scores, so the user might benefit from a warning, especially if the `tica__lag_time` upper bound is larger than ALL sequence lengths.

> if you have a handful of short trajectories I would say that shouldn't automatically discount short tica lag times
It's long lag times that would be the issue here.

**Comment by cxhernandez** [comment]
> Osprey should run a check on the config file to make sure that if tica__lag_time is specified, that its upper bound is less than, e.g., the shortest sequence.

I set up a custom dataset loader at some point that only loads trajectories that are longer than the largest tICA lagtime. Maybe this would be useful?

**Comment by mpharrigan** [comment]
@sryckbos the issue here is that *all* trajectories are too short, not just a handful

**Comment by sryckbos** [comment]
Hmm I see, fair enough.

**Comment by cxhernandez** [comment]
Honestly, I can't think of a good solution to this. I don't want to hardcode the `tica__lag_time` parameter since osprey is meant to be a general tool. I think that the error that's displayed is fairly informative and it's up to the user to make sure the parameter ranges are appropriate.
