### ISSUE TITLE
hyperopt search gets stuck

### ISSUE THREAD

**Issue by synapticarbors** [msmbuilder/osprey#149]
I've been playing around with osprey over the last week and I've noticed that pretty consistently, the hyperopt strategy gets stuck on the same guess of parameters. I've tried pre-seeding with a random search or GP, but after a while (or sometimes immediately), it just keeps on repeating the same parameter set resulting in slightly different scores. I've seen the same behavior using different MSMBuilder clustering schemes and parameter ranges on the same system (a very well-sampled folding data set). 

Has anyone else seen this behavior? Is this just a general weakness of hyperopt?

Maybe it would be good for Osprey to detect this behavior and either (1) exit with a warning that hyperopt is possibly stuck in a local minima, or (2) optionally, detect that hyperopt has chosen a parameter set that's already in the database and run one step of another strategy, probably just random by default, to try to get unstuck. This would maybe avoid those frustrating situations where a user goes and checks on an overnight, day or multi-day long run only to find that they've been burning cycles redoing the same calculation over and over again (I'm not that frustrated, personally, but one could imagine).

**Comment by rmcgibbo** [comment]
It seems pretty reasonable to me to skip re-running a calculation with identical parameters to a job that's already in the DB.

**Comment by milos1986** [comment]
I had encountered the Hyperopt bug too. I found this among the open issues on the Hyperopt github:
https://github.com/hyperopt/hyperopt/issues/276  ("Hyperopt always sampling the same points with TPE strategy  #276")

**Comment by synapticarbors** [comment]
Closed by #215
