### ISSUE TITLE
save_current_best functionality

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/osprey#151]
It might be nice to have a command that saves the current best fully fit model to a pickle file for later use.

**Comment by brookehus** [comment]
If one does multiple iterations of CV, would it just randomly choose the last one done? For example, if I find my best model by doing five iterations of 50/50 shuffle-split, which iteration- i.e. which randomly chosen 50% of the data gets modeled? If I were telling someone how to Osprey I would say that they should use CV to choose the best model, which by definition involves fitting to a subset of the data, but then should use those parameters to construct the best model on the _entire_ dataset. So maybe something that would make sense would be a sort of `ConstructBestModel` command that grabs the `current_best` parameters and fits all the data to a model, then saves it.

**Comment by cxhernandez** [comment]
Yup, that's I had in mind!

**Comment by cxhernandez** [comment]
done in #232
