### ISSUE TITLE
Update osprey skeleton

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/osprey#178]
Make sure all the options are here instead of most of the options. search strategy `grid` isn't listed

**Comment by mpharrigan** [comment]
different cross-validation schemes

**Comment by cxhernandez** [comment]
I've added a skeleton for every search strategy. CV schemes is probably a good idea as well. Ideally, skeleton could take bits and pieces from each and make a custom skeleton:

```bash
$ osprey skeleton -n config.yaml --search-strategy gp --cross-validator loo --dataset-loader joblib
```

**Comment by mpharrigan** [comment]
I'd rather have `conda skeleton` serve more as "interactive documentation", as currently written

**Comment by cxhernandez** [comment]
prefer to do this through #220
