### ISSUE TITLE
Issue with parallel jobs using PBS queue manager

### ISSUE THREAD

**Issue by jeiros** [msmbuilder/osprey#201]
Hi, 

I'm running Osprey on an HPC service which uses PBS Pro to manage the queues. My submission script is as follows:
```bash
#!/bin/sh
#PBS -l walltime=96:00:00
#PBS -l mem=8000mb
#PBS -l ncpus=8
#PBS -q pqchem
#PBS -j oe

module load anaconda/2.1.0
source activate osprey

for i in `seq 8`; do
	osprey worker /work/je714/osprey_test/config.yaml -n 10 > osprey.$PBS_JOBID.$i.log 2>&1 &
done
wait
```
And the estimator in my config file is:
```yaml
estimator:
    entry_point: msmbuilder.decomposition.tICA
    eval: |
        Pipeline([
                ('tica', tICA()),
                ('cluster', MiniBatchKMeans()),
                ('msm', MarkovStateModel(lag_time=1, n_timescales=10, verbose=False)),
        ])
    eval_scope: msmbuilder
```
I'm loading the data in pre-featurized trajectories stored in numpy arrays:

```yaml
dataset_loader:
  name: numpy
  params:
    filenames: arr*.npy
```

Some minutes after it runs, PBS kills my job with the following error: `=>> PBS: job killed: ncpus 11.85 exceeded limit 8 (sum)`. 

I've assumed this happens because somewhere msmbuilder is trying to run in parallel and that demands more cpus than available, but I haven't seen any mentions of parallelism in the `tICA` or `MarkovStateModel` docs.

I've then tried changing the clustering method to `KMeans` so I can use the `n_jobs=1` argument, and it again fails with the same error: `=>> PBS: job killed: ncpus 17.81 exceeded limit 8 (sum)`.

Do you have any suggestions to solve this?

**Comment by mpharrigan** [comment]
I think the eigensolvers in tica and msm spawn multiple threads by default. Try setting these environment variables http://stackoverflow.com/a/31622299

**Comment by jeiros** [comment]
Thanks for the quick response! That seems to have done the trick (it's been running for awhile without errors) 😄
