### ISSUE TITLE
Json dump suggestion

### ISSUE THREAD

**Issue by jeiros** [msmbuilder/osprey#207]
When using `osprey dump -o json ` I was wondering if it'd be more useful to store each of the `parameters` in separate name/value pairs, instead of in a single entry as a dictionary.

That way, when loading the json with `pd.read_json` for example, each of the parameters would be stored in a column. That feels more natural to me and allows for easier plotting: ```plt.scatter(df['tica__lag_time'], df['mean_test_score'])```

At the moment, to 'extract' each of the parameters in a different DataFrame, I have to do something like this:
```python
import pandas as pd
df = pd.read_json('dump.json')

params = pd.DataFrame(columns=list(df['parameters'][0].keys()))
for i, hyp_parms in enumerate(df['parameters']):
    params.loc[i] = hyp_parms

# Scatter plot with a single command
plt.scatter(params['tica__lag_time'], df['mean_test_score'])
```

If you think this is a good idea, maybe you could point me out what needs to be changed and I'd be happy to implement it.

**Comment by cxhernandez** [comment]
This sounds like a useful improvement to me! All the code for the `json` dump is contained [here](https://github.com/msmbuilder/osprey/blob/master/osprey/execute_dump.py#L16-L18).

**Comment by cxhernandez** [comment]
done in #212
