### ISSUE TITLE
Parallelize over n data splits for same parameters

### ISSUE THREAD

**Issue by rafwiewiora** [msmbuilder/osprey#230]
Hey guys, 

I'm doing 1 Osprey worker / model (`n=10`) right now and it takes between 5 minutes - 2.5 hours to complete a worker. So it would be nice to be able to parallelize not only over parameter choices, but also over the `n` data splits. 

Chatted with @cxhernandez about this - he pointed out this just needs the `n_jobs` in https://github.com/msmbuilder/osprey/blob/master/osprey/fit_estimator.py#L22 exposed.

**Comment by msultan** [comment]
Wont this cause horrific clashes if you have more than one worker running at the same time?

**Comment by cxhernandez** [comment]
Sure, but the default can be 1. We can also warn about this in the documentation.

**Comment by rafwiewiora** [comment]
> Wont this cause horrific clashes if you have more than one worker running at the same time?

What clashes are we talking about here? Running many workers is what I'm planning to do.

**Comment by cxhernandez** [comment]
If you run multiple multi-threaded workers naively on a single node, you can easily make your jobs more inefficient than a single worker on a single thread.

**Comment by cxhernandez** [comment]
done in #231!
