### ISSUE TITLE
Mapping integer variables from [0,1] in Gaussian Processes strategy 

### ISSUE THREAD

**Issue by RobertArbon** [msmbuilder/osprey#233]
This code doesn't seem correct for the `IntVariable` in `search_space.py`:  
```
    def point_from_gp(self, gpvalue):
        if self.warp is None:
            return int( self.min + ( gpvalue * (self.max - self.min) ) )
```
Shouldn't it return 
```
 int(np.floor( min( self.min + gpvalue * (self.max - self.min + 1), self.max ) ))
```
?

Reason: 

Let's say we have an integer variable that can take on values 1, 2, 3, 4, 5.  Call `x` the value returned from `point_from_gp`, then this function is:

|   gpvalue	| x  	|
|---	|---	|
|  [0.0, 0.25) 	|   1	|
|   [0.25, 0.5)	|   2	|
|   [0.5, 0.75)	|  3 	|
|   [0.75, 1)	|   4	|
|   1.0	|   5	|
 
using my suggested alteration the function becomes: 

|   gpvalue	| x  	|
|---	|---	|
|  [0.0, 0.2 ) 	|   1	|
|   [0.2, 0.4)	|   2	|
|   [0.4, 0.6)	|  3 	|
|   [0.6, 0.8)	|   4	|
|   [0.8, 1.0]	|   5	|
 
You can see more examples [here](https://github.com/RobertArbon/IntegerMapping/blob/master/Integer%20Mapping.ipynb)

It's also a problem for the warped variables but I haven't worked out the answer to that yet.

**Comment by RobertArbon** [comment]
For the warped variables I believe the solution (_one possible_ solution) is:
```
        rng = np.log(xmax-xmin+2)
        outvalue = np.exp(gpvalue * rng )
        return min(outvalue+xmin-1, xmax).astype(int)
```
rather than:
```
        rng = np.log(xmax) - np.log(xmin)
        outvalue = np.exp(np.log(xmin) + gpvalue * rng)
        return np.clip(outvalue, xmin, xmax).astype(int)
```

You can see some worked examples [here](https://github.com/RobertArbon/IntegerMapping/blob/master/Warped%20Integer%20Mapping.ipynb)

**Comment by cxhernandez** [comment]
done in #234
