### ISSUE TITLE
Question on available optimisation metrics

### ISSUE THREAD

**Issue by orestxherija** [msmbuilder/osprey#239]
I was wondering whether it is possible to use a varying suite of metrics when doing, say, k-fold cross-validation. More specifically, if I wanted to use logloss, RMSE or some other performance metric to find optimal hyperparameters, would I be able to do so? As far as I have seen, the `cv` field of the `yaml` file does not accept arguments pertaining to different scoring functions. Is there a standard metric that `osprey` uses for, say, all binary classification tasks?

**Comment by brookehus** [comment]
There is a `scoring` field; see [here](https://github.com/msmbuilder/osprey/blob/master/osprey/config.py#L15).

**Comment by orestxherija** [comment]
Thanks a lot, @brookehus !
