### ISSUE TITLE
refactoring

### ISSUE THREAD

**Issue by RobertArbon** [msmbuilder/osprey#246]
Hi folks, 

I'm refactoring my fork of Osprey.  I thought I'd give you a heads up as you might want to accept the changes but then again you may not as it's quite a change. 

I'm changing the structure so there's three main strategies: `Grid`, `Random` and `Bayesian`.  The Bayesian strategy will implement the Gaussian processes (and eventually TPE) models. 

The Bayesian strategy will load a `SurrogateModel` class (e.g. Gaussian Process, TPE, Regression Trees, *whatever*) and an `AcquisitionFunction` class.  

Once that's done I was planning on making the Gaussian Process model use `PyMC3`  or `GPFlow`.  

thoughts, comments, ideas etc?

**Comment by cxhernandez** [comment]
That sounds like a great plan to me! I think `PyMC3` might be preferable since it has a more stable development pipeline and would probably be more flexible for acquisition function development later on. I've been burned by `GPy` too many times in the past.... That being said looking forward to seeing the PR!

**Comment by RobertArbon** [comment]
Ok great!  I've just merged the latest master branch...should probably finish it off by end of this week.  

Yeah, `GPy` needs to go, if not solely because of the horrendous documentation.

**Comment by RobertArbon** [comment]
Hi folks, 

just finished my PhD where I worked out many of the details for a PyMC3 implementation, so I'll be devoting more time to this now. 

However! I've borked my fork this so I may cancel the refactoring PR and start again. Hopefully not though. 

Thanks for your patience. 

Rob
