### ISSUE TITLE
Hyperparameter optimization stalls

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/osprey#71]
I'm not sure MOE is working like it's supposed to at times. In this case seems like it's sample along the parameter bounds and sampling the same points.

```
----------------------------------------------------------------------
Beginning iteration                                             8 / 10
----------------------------------------------------------------------
Loading trials database: sqlite:///villin.db...
History contains: 125 trials
Choosing next hyperparameters with moe...
  {'tica__n_components': 2, 'tica__lag_time': 1, 'cluster__n_clusters': 100, 'tica__gamma': 0.099999999999999895, 'featurizer__types': ['phi', 'psi', 'chi1']}
(moe took 6.656 s)

[Parallel(n_jobs=1)]: Done   1 jobs       | elapsed:  1.0min
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  5.6min finished
[CV] Using MSMBuilder API n_samples averaging
[CV]   n_train_samples: [717706, 716515, 717335, 711555, 723199]
[CV]   n_test_samples: [730784, 731975, 731155, 736935, 725291]
Loading trials database: sqlite:///villin.db...

....

----------------------------------------------------------------------
Beginning iteration                                            10 / 10
----------------------------------------------------------------------
Loading trials database: sqlite:///villin.db...
History contains: 171 trials
Choosing next hyperparameters with moe...
  {'tica__n_components': 2, 'tica__lag_time': 1, 'cluster__n_clusters': 100, 'tica__gamma': 0.099999999999999895, 'featurizer__types': ['phi', 'psi', 'chi1']}
(moe took 10.258 s)

[Parallel(n_jobs=1)]: Done   1 jobs       | elapsed:  1.2min
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  6.3min finished
[CV] Using MSMBuilder API n_samples averaging
[CV]   n_train_samples: [708766, 708440, 725087, 722092, 727750]
[CV]   n_test_samples: [739724, 740050, 723403, 726398, 720740]
Loading trials database: sqlite:///villin.db...
```

**Comment by cxhernandez** [comment]
this also happens with hyperopt_tpe

**Comment by rmcgibbo** [comment]
Perhaps this suggests that it thinks these are the best values?

**Comment by cxhernandez** [comment]
It could be, but I'm skeptical. I've had random search find better values, and even with those in the history MOE results didn't update. I also know @msultan has run into this issue.

**Comment by rmcgibbo** [comment]
you have more practical experience with MOE than I do, so I don't have any great suggestions. The best thing is probably to try playing around with the different hyperparameters MOE accepts using one of your existing trails databases.

**Comment by msultan** [comment]
@cxhernandez what was your train/test split. I was getting a similar behavior where the same model was being fit by multiple workers. I might be wrong but I think the Gaussian prior widths that MOE uses might need to be substantially increased. 
It could also be that given the randomness of the train/test + equilibrium requirements for  both, MOE is just unsure about what the actual score is given the set of parameters so it is refitting? I haven't read the MOE paper so this is pure conjecture at this point. 
Empirically, right now it might be best to start with a few hundred random models which might get MOE to converge faster.
