### ISSUE TITLE
PBS array job example?

### ISSUE THREAD

**Issue by kyleabeauchamp** [msmbuilder/osprey#79]
Would it make more sense to control jobs using PBS array jobs?  For example, wouldn't the following be the easiest way to control a number of "rounds" of optimization with finite resources?  

```
cat submit.sh
[...]
#PBS -l nodes=1:ppn=8
[...]
osprey worker tica.yaml -n 1 > osprey.$PBS_JOBID.log

qsub submit.sh -q gpu -t 0-25%3
```

I can file a PR if people think this is a clean way to do things...

**Comment by rmcgibbo** [comment]
Array jobs are only on SGE, right?

**Comment by rmcgibbo** [comment]
But yeah, I like them a lot. You can also use the `-t` obviously inside the job script, not just on the command line.

**Comment by kyleabeauchamp** [comment]
Our cluster is Torque / MOAB (https://github.com/cBio/cbio-cluster/wiki/MSKCC-cBio-Cluster-User-Guide)

**Comment by rmcgibbo** [comment]
Oh cool. I didn't realize torque had that feature too.
